# frontend/cloudbuild.yaml
steps:
# Step 1: Install project dependencies
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

# Step 2: Build the production version of the React app
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']

# Step 3: Install the Firebase command-line tool
- name: 'gcr.io/cloud-builders/npm'
  args: ['install', '-g', 'firebase-tools']

# Step 4: Deploy the 'build' folder to Firebase Hosting
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'firebase', 'deploy', '--only', 'hosting', '--project', '$PROJECT_ID']